#!/bin/bash
# Script para listar estrutura do projeto (opcional, para Linux/Mac)

echo "🎭 Escape Puzzle Voucher - Estrutura do Projeto"
echo "=============================================="
echo ""
echo "Ficheiros Principais:"
echo "  - index.html (3.6 KB) - Página principal"
echo "  - assets/style.css (17.4 KB) - Estilos"
echo "  - assets/utils.js (6.2 KB) - Configuração e utilidades"
echo "  - assets/puzzles.js (11.8 KB) - Os 3 desafios"
echo "  - assets/voucher.js (8.1 KB) - Voucher e confettis"
echo "  - assets/app.js (4.3 KB) - Navegação"
echo ""
echo "Documentação:"
echo "  - START.md - Guia rápido (COMENÇA AQUI!)"
echo "  - README.md - Documentação completa"
echo "  - CUSTOMIZACAO.md - Como personalizar"
echo "  - FORMSPREE_SETUP.md - Setup de emails"
echo "  - GITHUB_PAGES_DEPLOY.md - Deploy online"
echo "  - FEATURES.md - Lista de funcionalidades"
echo "  - RESUMO.md - Resumo visual do projeto"
echo ""
echo "Configuração Git:"
echo "  - .gitignore - Ficheiros a ignorar"
echo "  - .github/workflows/deploy.yml - Deploy automático"
echo ""
echo "Total: ~100 KB incluindo documentação"
echo "Código: ~50 KB"
echo ""
echo "🚀 Para começar: Abre index.html no browser!"
echo ""
